import Head from "next/head";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/Icons/GitHub";
import { colors } from "../styles/theme";

export default function Home() {
  return (
    <div>
      <Head>
        <title>devter</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AppLayout>
        <section>
          <img src="/devter-logo.png" alt="logo" />
          <h1>Devter</h1>
          <h2>
            Talk About development 👨‍💻 👩‍💻 <br />
            with developers
          </h2>
          <div>
            <Button>
              <GitHub fill='#fff' width={24} height={24}/>
              Login with Github
            </Button>
          </div>
        </section>
      </AppLayout>
      <style jsx>{`
        img {
          width: 120px;
        }
        section {
          display: grid;
          height: 100%;
          place-items: center;
          place-content: center;
        }
        h1 {
          color: ${colors.secondary};
          font-weight: 800;
          margin-bottom: 21px;
        }
        h2 {
          color: ${colors.primary};
          font-size: 16px;
          margin: 0;
        }
        div {
          margin-top: 16px;
        }
      `}</style>
    </div>
  );
}
